version: '3'
services:
  postgres:
    image: 'postgres:12'
    container_name: 'cms-employee'
    ports:
      - '54320:5432'
    volumes:
      - cms_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'employee'
  # pgadmin:
  #   image: dpage/pgadmin4
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: pwdpwd
  #   volumes:
  #     - pgadmin:/root/.pgadmin
  #   ports:
  #     - "5050:80"
volumes:
  cms_dbdata:
  # pgadmin:
